version: "3.9"
services:
  ##### Add the next two services to your docker-compose file for full ssl support ######
  ssl-service:
    image: europe-west6-docker.pkg.dev/mtc-dev/mtc-ethz/ssl-service:latest
    build: ./ssl-service
    ports:
      - 443:443
      - 80:80
    volumes:
      - "letsencrypt:/etc/letsencrypt"
      - "var_letsencrypt:/var/lib/letsencrypt"
    depends_on:
      certbot:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    command: certonly -n --standalone --agree-tos --email ${SSL_EMAIL:?err} -d
      ${BASE_URL:?err} -d www.${BASE_URL:?err}
    volumes:
      - "letsencrypt:/etc/letsencrypt"
      - "var_letsencrypt:/var/lib/letsencrypt"

  #  Add your frontend configuration here
  frontend:
    build: ./example-frontend
    restart: unless-stopped

volumes:
  letsencrypt: {}
  var_letsencrypt: {}
