version: "3.9"
services:
  ##### Add the next three services to your docker-compose file for full ssl support ######
  ssl-service:
    image: europe-west6-docker.pkg.dev/mtc-dev/mtc-ethz/ssl-service
    container_name: ssl-service
    build: ./ssl-service
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "letsencrypt:/etc/letsencrypt"
    env_file:
      - .env
    restart: unless-stopped

  certbot:
    image: europe-west6-docker.pkg.dev/mtc-dev/mtc-ethz/ssl-service-certbot
    container_name: certbot
    build: ./certbot
    env_file:
      - .env
    volumes:
      - "letsencrypt:/etc/letsencrypt"
    # restart: unless-stopped (optional)

    # Add your frontend configuration here
  frontend:
    container_name: frontend
    build: ./example-frontend
    restart: unless-stopped

  # Add your backend configuration here
  backend:
    container_name: backend
    build: ./example-backend
    restart: unless-stopped
    env_file:
      - .env

volumes:
  letsencrypt: {}
