version: "3.9"
services:
  ##### Add the next two services to your docker-compose file for full ssl support ######
  ssl-service:
    build: ./ssl-service
    ports:
      - 443:443
    volumes:
      - "letsencrypt:/etc/letsencrypt"
      - "var_letsencrypt:/var/lib/letsencrypt"
    env_file:
      - .env
    command: /src/scripts/run_nginx.sh
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    command: certonly -n --standalone --agree-tos --email ${SSL_EMAIL?err} -d
      ${BASE_URL?err} -d ${WWW_URL?err}
    ports:
      - 80:80
    volumes:
      - "letsencrypt:/etc/letsencrypt"
      - "var_letsencrypt:/var/lib/letsencrypt"

  #  Add your frontend configuration here
  frontend:
    build: ./example-frontend
    ports:
      - 81:81
    restart: unless-stopped
    depends_on:
      - ssl-service

volumes:
  letsencrypt: {}
  var_letsencrypt: {}
